### ISSUE TITLE
Assignment Day03

### ISSUE THREAD

**Issue by NoyRavensary** [AdiBarelMeisel/AdiBarelMeisel.github.io#1]
Hey, I am Noy
Your website looks really great.
It would be nice if you added some recipes of your favorite baking's. :) 
@szabgab

**Comment by AdiBarelMeisel** [comment]
Thank you I will look for some interesting recipe :)
@szabgab

**Comment by AdiBarelMeisel** [comment]
Thank you I will look for some interesting recipe :)
@szabgab
